import NextAuth, { type NextAuthConfig } from "next-auth";
import Google from "next-auth/providers/google";
import { isAllowlisted, parseAllowlist } from "@/server/auth/allowlist";
import { findUserByGoogleSub, findUserById } from "@/server/repositories/user";
import { upsertUserOnSignIn } from "@/server/services/auth";


// ============================================================================
// Auth.js v5 — Google provider + env-var email allowlist (UC-01, ADR-2, ADR-3).
//
// Sign-in flow (PRD C3, ARCH §3.1, §3.2):
//   1. `signIn` callback: normalize email (trim + lowercase) and check against
//      `ALLOWED_EMAILS`. Return `false` → user lands on `/[locale]/403`
//      (PRD C3). Returning `false` also drops any partial state (no session,
//      no DB row) — `signIn` only commits the upsert after the allowlist
//      check passes (ARCH §3.2 rule 2).
//   2. On allow: upsert `app_user` by `google_sub`. On first insert, also
//      insert `profile_settings(currency='EUR')` in the same transaction
//      (PRD UC-01, §5.3).
//   3. `jwt` callback resolves the internal `app_user.id` by `google_sub`
//      on first sign-in and stores it on the token. `session` callback
//      exposes it as `session.user.id`. Server code never trusts
//      client-supplied user ids (ARCH §3.2 rule 3) — `requireUserId()` reads
//      it from the session via `auth()`.
//   4. `pages.error = '/403'` so the built-in error route renders our i18n
//      403 page (UC-01 screen 2).
//
// Session strategy: JWT (ADR-3). We don't use an Auth.js DB adapter because
// our `app_user` table is the source of truth and the JWT carries the
// internal id directly. `AUTH_SECRET`, `AUTH_GOOGLE_ID`, `AUTH_GOOGLE_SECRET`
// come from env (ARCH §3.2 rule 5); `AUTH_GOOGLE_ID/SECRET` are inferred
// from the provider id by Auth.js v5, but we read them explicitly to keep
// the link obvious and to make local-dev failures self-explanatory.
//
// Google provider prompt: intentionally omitted. Without `prompt`, Google
// silently re-authenticates the user's last-used account when a Google
// session is already active, skipping the account chooser — the right
// default for a single-tenant, allowlist-gated app where each user has one
// relevant Google identity. If a future need arises for explicit account
// switching (e.g. a "switch account" button), pass
// `authorizationParams: { prompt: "select_account" }` to that specific
// `signIn()` call rather than forcing the picker on every sign-in.
// ============================================================================


function getAllowedEmails(): ReadonlySet<string> {
  return parseAllowlist(process.env.ALLOWED_EMAILS);
}


export const authConfig: NextAuthConfig = {
  trustHost: true,
  secret: process.env.AUTH_SECRET,
  session: { strategy: "jwt" },
  pages: {
    signIn: "/sign-in",
    error: "/403",
  },
  providers: [
    Google({
      clientId: process.env.AUTH_GOOGLE_ID,
      clientSecret: process.env.AUTH_GOOGLE_SECRET,
    }),
  ],
  callbacks: {
    async signIn({ profile }) {
      const allowlist = getAllowedEmails();
      if (!isAllowlisted(profile?.email, allowlist)) {
        return false;
      }
      const googleSub = profile?.sub;
      if (typeof googleSub !== "string" || googleSub.length === 0) {
        return false;
      }
      const email = profile?.email;
      if (typeof email !== "string" || email.length === 0) {
        return false;
      }
      // First-time provisioning lives in the service so the transaction is
      // owned by the domain layer (ARCH §5 rule 3). On repeat sign-ins the
      // service is a cheap lookup.
      await upsertUserOnSignIn({
        googleSub,
        email,
        displayName: profile?.name ?? null,
        avatarUrl: profile?.picture ?? null,
      });
      return true;
    },
    async jwt({ token, account, profile }) {
      // Resolve the internal `app_user.id` from the Google `sub` on first
      // sign-in and cache it on the token. The Google `sub` lives on
      // `account.providerAccountId` (the OAuth provider's account id, NOT
      // `user.id` — without an Auth.js DB adapter, `user.id` in this callback
      // is a freshly-minted random UUID generated by `@auth/core`'s
      // `handleLoginOrRegister`). `profile.sub` is the same value, kept as a
      // belt-and-suspenders fallback. On subsequent calls `account` and
      // `profile` are undefined and we re-use the cached `token.userId`.
      //
      // We also store Google profile info on the token so we can re-provision
      // the user if the DB is reset but the session cookie persists.
      if (token.userId) {
        // Verify the user still exists in the DB (handles DB reset scenario)
        const existing = await findUserById(token.userId);
        if (existing) {
          return token;
        }
        // User doesn't exist — try to re-provision using stored profile info
        const storedGoogleSub = token.googleSub as string | undefined;
        const storedEmail = token.email as string | undefined;
        if (storedGoogleSub && storedEmail) {
          const created = await upsertUserOnSignIn({
            googleSub: storedGoogleSub,
            email: storedEmail,
            displayName: (token.displayName as string) ?? null,
            avatarUrl: (token.avatarUrl as string) ?? null,
          });
          token.userId = created.id;
          return token;
        }
        // No profile info available — invalidate session
        return {};
      }
      const googleSub =
        account?.provider === "google" ? account.providerAccountId : profile?.sub;
      if (typeof googleSub !== "string" || googleSub.length === 0) {
        return token;
      }
      // Store Google profile info on the token for potential re-provisioning
      if (profile?.email) {
        token.googleSub = googleSub;
        token.email = profile.email;
        token.displayName = profile?.name ?? null;
        token.avatarUrl = profile?.picture ?? null;
      }
      const internal = await findUserByGoogleSub(googleSub);
      if (internal) {
        token.userId = internal.id;
      } else if (profile?.email && profile?.email_verified) {
        // User has a valid Google session but doesn't exist in our DB.
        // This can happen if the DB was reset but the Google session persists.
        // Create the user now using the profile information.
        const created = await upsertUserOnSignIn({
          googleSub,
          email: profile.email,
          displayName: profile?.name ?? null,
          avatarUrl: profile?.picture ?? null,
        });
        token.userId = created.id;
      }
      return token;
    },
    async session({ session, token }) {
      const userId = (token as { userId?: string }).userId;
      const avatarUrl = (token as { avatarUrl?: string | null }).avatarUrl;
      if (typeof userId === "string" && userId.length > 0 && session.user) {
        session.user.id = userId;
      }
      if (typeof avatarUrl === "string" && avatarUrl.length > 0 && session.user) {
        session.user.image = avatarUrl;
      }
      return session;
    },
  },
};


export const { handlers, auth, signIn, signOut } = NextAuth(authConfig);