name: common-ci
on:
  workflow_call:
    inputs:
      should_push:
        required: false
        type: boolean
        default: true
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@11.22.0 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Enable pnpm
        run: corepack enable && corepack prepare pnpm@11.22.0 --activate
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm run test:unit
  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [lint, tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        if: ${{ inputs.should_push }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from package.json
        id: extract_version
        run: |
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ inputs.should_push }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/monthly-expenses:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/monthly-expenses:${{ env.APP_VERSION }}
